"use client";
import { useState } from "react";

const views = {
  Product:["The promise","Owners can bring colleagues into the right account.","We are building team invitations in four useful slices. Email delivery is active now; invitation creation is proven.",["Invitation creation — proven","Email delivery — working","Acceptance — waiting","Manage invitations — waiting"]],
  Flow:["How it behaves","Create → deliver → accept → join","The owner creates a link, delivery sends it, the invited person accepts, and membership is created in the intended account.",["Owner creates invite","System sends link","Recipient accepts","Account gains member"]],
  Architecture:["How it is shaped","You approve the direction. Conductor owns the work loop.","Switch preserves project continuity. Conductor understands, shapes, builds, peer-reviews, proves and completes the work through bounded model jobs.",["Switch — preserves continuity","Conductor — owns the complete loop","Models — perform bounded jobs","Repository — holds shared truth"]],
  Detail:["Build and proof","The rigor is present without becoming required reading.","Sequences, interfaces, recovery paths, fixtures, generated prompts and telemetry remain available for whoever needs them.",["Interfaces and states","Recovery and edge cases","Tests linked to measures","Full evidence trail"]],
} as const;
type ViewName=keyof typeof views;

export default function Home(){
 const [view,setView]=useState<ViewName>("Product"); const current=views[view];
 return <main>
  <nav className="nav"><a className="brand" href="#top">KERD <span>Model-ready work</span></a><div className="navLinks"><a href="#how">How it works</a><a href="#work">Live work view</a><a href="#proof">Why trust it</a></div></nav>
  <section className="hero" id="top"><div className="eyebrow">DEFINE THE RESULT. LET THE MODEL DO ITS BEST WORK.</div><h1>Create what you want.<br/><em>Not the perfect prompt.</em></h1><p className="heroCopy">Whether you are shaping a product, running a project, making an executive decision, researching a question, creating a story, or building software: describe the result in ordinary language. Conductor prepares clear, measurable work for the right model, then shows you what happened and why it is trustworthy.</p><div className="heroActions"><a className="primary" href="#how">See the process</a><a className="secondary" href="#work">Open an example work view</a></div><div className="promise"><span>Fewer avoidable questions</span><span>Freedom without drift</span><span>Fast with a quality floor</span></div></section>
  <section className="section" id="how"><Header n="01" title={<>Enough clarity,<br/>without the burden.</>} text="You provide intent and consequential decisions. Conductor carries the prompting, context, autonomous build loop, peer review and proof."/><div className="steps"><Step n="1" title="Tell us what you want">Start in your own words. A guided interview retrieves known answers and asks only what can change the work.</Step><Step n="2" title="Approve the direction">See the outcome, connected parts, flow, proof, boundaries, assumptions, resources and stopping point. No giant specification.</Step><Step n="3" title="Let Conductor run">Conductor sizes bounded jobs for the right models, then builds, peer-reviews, proves and improves without routine interruption.</Step><Step n="4" title="Receive a proven result">The builder does not grade itself. Every agreed measure passes independent review before Conductor completes.</Step></div></section>
  <section className="workSection" id="work"><Header n="02" title="See the level you need." text="One underlying truth, from product direction to implementation evidence. Choose the depth required for this decision."/><div className="workShell"><div className="workTop"><div><small>TEAM INVITATIONS</small><strong>Standard · Slice 2 of 4</strong></div><div className="live"><i/> Working now</div></div><div className="viewTabs" role="tablist">{(Object.keys(views) as ViewName[]).map((name,i)=><button key={name} onClick={()=>setView(name)} className={view===name?"active":""} aria-selected={view===name}>{i+1}. {name}</button>)}</div><div className="viewBody"><div><small>{current[0]}</small><h3>{current[1]}</h3><p>{current[2]}</p></div><ul>{current[3].map((item,i)=><li key={item}><span className={i===0?"done":i===1?"now":"wait"}/>{item}</li>)}</ul></div><div className="decision"><span>WHAT NEEDS YOU?</span><strong>No decision right now.</strong><p>Next review after email delivery proof passes.</p></div></div></section>
  <section className="section"><Header n="03" title={<>Three levels.<br/>One quality floor.</>} text="The process grows only when consequence, uncertainty or proof requires it."/><div className="levelGrid"><Level name="QUICK" title="Narrow and reversible" example="Correct one sourced claim">Clear outcome, boundaries and mechanical proof. Few or no questions.</Level><Level name="STANDARD" title="A complete useful feature" example="Add invitation delivery" featured>Measurable outcome, focused context and decision rights. The model owns implementation.</Level><Level name="IMPORTANT / DEEP" title="Consequential or uncertain" example="Migrate live customer data">Recovery, deeper reasoning and independent review before irreversible effects.</Level></div></section>
  <section className="jobs"><div><span>04 / AUTONOMOUS LOOP</span><h2>One Conductor. Bounded model jobs.</h2><p>Conductor builds, peer-reviews, proves and improves against the same measures. Models do bounded work rather than holding open-ended chats. Switch preserves continuity across the project.</p></div><div className="jobFlow"><b>Build</b><i>↔</i><b>Peer review</b><i>↔</i><b>Prove</b><i>↔</i><b>Improve</b></div></section>
  <section className="proof" id="proof"><span>05 / THE STANDARD</span><blockquote>“Get to a proven result quickly, without purchasing speed through lower quality—or quality through unnecessary ceremony.”</blockquote><div><p><strong>Fixed:</strong> outcome, proof, boundaries and decision ownership.</p><p><strong>Adapted:</strong> prompt shape, context, tools, examples and effort.</p><p><strong>Measured:</strong> correctness, evidence, time, cost, interruptions and rework.</p></div></section>
  <footer><div className="brand">KERD <span>Model-ready work</span></div><p>Working product concept · prepared for independent review</p></footer>
 </main>
}
function Header({n,title,text}:{n:string,title:React.ReactNode,text:string}){return <div className="sectionHead"><span>{n} / THE EXPERIENCE</span><h2>{title}</h2><p>{text}</p></div>}
function Step({n,title,children}:{n:string,title:string,children:React.ReactNode}){return <article><b>{n}</b><h3>{title}</h3><p>{children}</p></article>}
function Level({name,title,example,featured,children}:{name:string,title:string,example:string,featured?:boolean,children:React.ReactNode}){return <article className={featured?"featured":""}><span>{name}</span><h3>{title}</h3><p>{children}</p><b>Example: {example}</b></article>}
