#!/usr/bin/env python3
"""Review synthetic labels; optional GitHub render sends no project/user content."""
import argparse
import importlib.util
import json
from html.parser import HTMLParser
from pathlib import Path
import urllib.request

class Tables(HTMLParser):
    def __init__(self):
        super().__init__()
        self.tables = self.rows = self.depth = 0
        self.active = []
    def handle_starttag(self, tag, attrs):
        if tag == "table": self.tables += 1
        if tag == "tr": self.rows += 1
        if tag in {"td", "th"}: self.depth += 1
        if self.depth and tag in {"a", "script", "em", "strong", "code", "img", "del", "input"}:
            self.active.append({"tag": tag, "attributes": dict(attrs)})
    def handle_endtag(self, tag):
        if tag in {"td", "th"}: self.depth -= 1

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("artifact", type=Path)
parser.add_argument("--label", choices=("submitted", "corrected"), required=True)
parser.add_argument("--github", action="store_true", help="Render synthetic data using GitHub's anonymous Markdown API")
args = parser.parse_args()
spec = importlib.util.spec_from_file_location("reviewed_preview", args.artifact / "pickup_preview.py")
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)
packet = dict(status="pickup_prepared", branch="https://example.com", commit="contact@example.com",
    clean_at_check=True, synchronized=False, note="SYNTHETIC-NOTE-NOT-FOR-OUTPUT",
    private_id="SYNTHETIC-UNKNOWN", sources=[dict(file="see www.example.com",
    selection="| `tick` <script>x</script> *em* [link](x)\n## Now",
    content="SYNTHETIC-PRIVATE-BODY café")])
markdown = module.summarize_markdown(packet)
assert not any(secret in markdown for secret in (packet["note"], packet["private_id"], packet["sources"][0]["content"]))
result = dict(renderer="not run", packet=packet, markdown=markdown)
if args.github:
    request = urllib.request.Request("https://api.github.com/markdown",
        data=json.dumps(dict(mode="gfm", text=markdown)).encode(),
        headers={"Content-Type": "application/json", "Accept": "text/html", "User-Agent": "Kerd-isolated-review"})
    with urllib.request.urlopen(request, timeout=30) as response:
        html = response.read().decode()
        result.update(renderer="GitHub Markdown API, mode=gfm, no repository context",
                      observed_at=response.headers.get("Date"), html=html)
    parsed = Tables()
    parsed.feed(html)
    result.update(tables=parsed.tables, rows=parsed.rows, active_cell_elements=parsed.active)
    # Heading permalinks generated by GitHub outside cells are deliberately excluded.
    assert parsed.tables == 2 and parsed.rows == 9
    assert bool(parsed.active) == (args.label == "submitted"), result
target = Path(__file__).with_name(f"{args.label}-render.json")
target.write_text(json.dumps(result, ensure_ascii=True, indent=2) + "\n")
print(json.dumps({key: result.get(key) for key in ("renderer", "tables", "rows", "active_cell_elements")}))
