#!/usr/bin/env python3
"""Did the handoff record what the session produced?

    python3 tools/gates/fidelity.py [--json] [--since <ref>]

The boundary's own accepted-unknown, made checkable. `docs/product/switch-fidelity.md`
records it plainly: *"There is no check today that a pickup restored what the
close recorded."* Slice 1 shipped unverified because of it, and on 2026-08-07
Tony declined to close a session on exactly that ground — "no can't take the
risk".

**What it checks.** Every artifact the session produced — files added or
changed in the commit range — must be *reachable* from the three files a pickup
actually reads: `CONTEXT.md`, `TODO.md`, and the newest log in
`kivna/sessions/`. An artifact nobody mentions is not lost from disk, but it is
lost from the handoff: the next session has no path to it, which is the failure
this repo has now hit at its own highest altitude (`docs/design/conductor-role.md`
sat unbuilt for three days because nothing pointed at it).

**What it does NOT check, and these limits are the point of stating them.**

1. *Reachability, never comprehension.* A path named in a sentence passes even
   if the sentence misdescribes it. Same declared limit as grounding-was-read:
   the machine can prove a reference resolves and cannot prove anyone
   understood it.
2. **File reachability is not FINDING reachability, and this one has already
   bitten.** The check asks whether a produced *file* is named. It cannot ask
   whether a *finding inside* that file is. On 2026-08-07 it passed green while
   `docs/product/funnel-driver.md` held a live contradiction between a standing
   decision and shipped skill text — the file was mentioned, the finding was
   unreachable, and product docs are not in the pickup's read set at all. Tony
   found it by asking "will that be picked up next session?", which no check
   asked. A finding that must survive a boundary belongs in `CONTEXT.md` or
   `TODO.md` in full, not behind a pointer.

A check that claimed more than this would be the "model choosing to comply"
failure wearing a green tick.

Exit 0 when everything produced is reachable, 1 when something is not. Noise is
the enemy of a check nobody heeds, so generated and immutable artifacts are
exempt by rule, and each exemption is named in `EXEMPT` with its reason.
"""

import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

# The three files a pickup reads. Defined by skills/switch/SKILL.md Switch In;
# if that read-set changes, this list changes with it or the check goes stale.
READ_SET = ["CONTEXT.md", "TODO.md"]

# Exempt from needing a mention, each with the reason it cannot be a handoff gap.
EXEMPT = [
    (r"^docs/plans/progress\.(excalidraw|svg|html)$",
     "generated by progress.py and CI-refused if stale — derived, never authored"),
    (r"^docs/plans/journey-.*\.(svg|html|excalidraw)$",
     "generated by gen_journey*.py from disk — derived, never authored"),
    (r"^kivna/sessions/",
     "the log IS the record; it cannot be required to mention itself"),
    (r"^docs/gates/",
     "immutable dated records, reachable by the board's route derivation"),
    (r"^\.claude-plugin/",
     "version manifests, checked by gate.py release"),
    (r"^(CONTEXT|TODO)\.md$",
     "the read set itself"),
]


def run(*args):
    try:
        return subprocess.run(args, cwd=ROOT, capture_output=True,
                              text=True, check=True).stdout
    except (subprocess.CalledProcessError, FileNotFoundError):
        return ""


def newest_log():
    logs = sorted((ROOT / "kivna" / "sessions").glob("*.md"))
    return logs[-1] if logs else None


def session_range(since=None):
    """Commits since the PREVIOUS boundary.

    The obvious anchor — "since the session log was last committed" — is wrong,
    and wrong in a way that makes the check pass vacuously: the log is written
    at the boundary, so that commit is usually the newest one and the range
    collapses to nothing. Observed on the first run: 2 commits inspected out of
    25. The honest anchor is the most recent commit that ADDED a session log —
    a boundary by definition, and stable when a session appends to its own log
    mid-sitting."""
    if since:
        return since
    # Anchor on the most recent commit that ADDED a session log. That commit is
    # a boundary by definition, and unlike "last commit touching the log" it
    # does not move when a session appends to its own log mid-sitting — which
    # switch-fidelity gap 13 actively encourages, and which silently shrank the
    # range to nothing on the first version of this check.
    shas = [s for s in run("git", "log", "--diff-filter=A", "--format=%H", "--",
                           "kivna/sessions/").splitlines() if s]
    if shas:
        return shas[0]
    return "HEAD~20"


def exempt(path):
    for pat, why in EXEMPT:
        if re.match(pat, path):
            return why
    return None


def check(since=None):
    base = session_range(since)
    changed = [p for p in run("git", "diff", "--name-only", f"{base}..HEAD").splitlines() if p]
    commits = [c for c in run("git", "log", "--format=%h %s", f"{base}..HEAD").splitlines() if c]

    haystack = ""
    for f in READ_SET:
        p = ROOT / f
        if p.exists():
            haystack += p.read_text()
    log = newest_log()
    if log:
        haystack += log.read_text()

    unreachable, exempted = [], []
    for path in changed:
        why = exempt(path)
        if why:
            exempted.append({"path": path, "reason": why})
            continue
        name = Path(path).name
        # Reachable if the full path or the bare filename is named anywhere a
        # pickup will read. Bare filename counts: prose legitimately says
        # "funnel-steps.md" without the directory.
        if path in haystack or name in haystack:
            continue
        unreachable.append(path)

    return {
        "base": base,
        "commits": len(commits),
        "changed": len(changed),
        "exempt": len(exempted),
        "unreachable": unreachable,
        "ok": not unreachable,
    }


def at_boundary():
    """True when HEAD writes a session log — the only moment this question is
    meaningful.

    Running on every push would be wrong and would train people to ignore the
    red: a work commit that adds a file legitimately has nothing in the log yet,
    because the log is written at the boundary. Firing there would make CI red
    for the entire duration of normal work. The boundary commit is exactly the
    moment everything produced should be reachable, so that is where it bites."""
    touched = run("git", "show", "--name-only", "--format=", "HEAD").splitlines()
    return any(p.startswith("kivna/sessions/") for p in touched if p)


def main(argv):
    since = None
    if "--since" in argv:
        since = argv[argv.index("--since") + 1]

    if not since and "--force" not in argv and not at_boundary():
        msg = ("fidelity: skipped — HEAD is not a boundary commit "
               "(it does not write a session log)")
        print(json.dumps({"skipped": True, "reason": msg}, indent=1)
              if "--json" in argv else
              msg + "\n  the check bites at the boundary, where the handoff is "
              "actually made.\n  run with --force to check anyway.")
        return 0

    res = check(since)

    if "--json" in argv:
        print(json.dumps(res, indent=1))
        return 0 if res["ok"] else 1

    print(f"fidelity — did the handoff record what the session produced?")
    print(f"  range: {res['base']}..HEAD · {res['commits']} commit(s) · "
          f"{res['changed']} file(s) changed · {res['exempt']} exempt")
    if res["ok"]:
        print("  every artifact produced is named in CONTEXT.md, TODO.md, or the newest log")
        print("\nfidelity: clean")
        print("  (reachability only — this cannot prove anything was understood)")
        return 0
    print(f"\n  {len(res['unreachable'])} artifact(s) produced and named nowhere a pickup reads:")
    for p in res["unreachable"]:
        print(f"    {p}")
    print("\n  fix: name each in CONTEXT.md, TODO.md, or this session's log —")
    print("       whichever is the honest home. An artifact nobody points at is")
    print("       unreachable to the next session even though it is on disk.")
    print("\nfidelity: 1 or more artifacts unreachable")
    return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv))
